# Site settings
title: Jekyll shop powered by Snipcart
email: adammichaelwood@gmail.com
description: Here's a quick demo showing the integration between Snipcart, Jekyll, and Intempt. We hope you like it!
baseurl: "/snipcart-jekyll-integration/" # the subpath of your site, e.g. /blog/
url: "http://adammichaelwood.com" # the base hostname & protocol for your site
twitter_username: adammichaelwood
github_username:  adammichaelwood
api_key: YjdiNWIyOTUtZTIyMy00MWMwLTkwNDUtMzI1M2M2NTgxYjE0

# Build settings
markdown: kramdown
collections:
  products:
    output: true
